import type {
  Profile,
  Brand,
  Slime,
  CollectionLog,
  ActivityFeedItem,
  Drop,
  UserCollectionSummary,
} from "./types";

export const MOCK_PROFILE: Profile = {
  id: "user-001",
  username: "slimequeen_jen",
  full_name: "Jennifer M.",
  avatar_url: null,
  bio: "🫧 Butter slime devotee. 400+ in collection. Haul reviewer & drop tracker obsessive.",
  is_premium: true,
  is_verified: false,
  created_at: "2024-09-01T00:00:00Z",
  updated_at: "2026-03-01T00:00:00Z",
};

export const MOCK_BRANDS: Brand[] = [
  {
    id: "b1000000-0000-0000-0000-000000000001",
    slug: "peachybbies",
    name: "Peachybbies",
    logo_url: null,
    shop_url: "https://peachybbies.com",
    instagram_handle: "peachybbies",
    tiktok_handle: "peachybbies",
    is_verified: true,
    owner_id: null,
    avg_shipping: 4.7,
    avg_customer_service: 4.8,
    total_brand_ratings: 2341,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "b1000000-0000-0000-0000-000000000002",
    slug: "sloomoo",
    name: "Sloomoo Institute",
    logo_url: null,
    shop_url: "https://sloomooinstitute.com",
    instagram_handle: "sloomooinstitute",
    tiktok_handle: "sloomoo",
    is_verified: true,
    owner_id: null,
    avg_shipping: 4.5,
    avg_customer_service: 4.6,
    total_brand_ratings: 1892,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "b1000000-0000-0000-0000-000000000003",
    slug: "craftedslimes",
    name: "Crafted Slimes",
    logo_url: null,
    shop_url: "https://craftedslimes.com",
    instagram_handle: "craftedslimes",
    tiktok_handle: "craftedslimes",
    is_verified: true,
    owner_id: null,
    avg_shipping: 4.9,
    avg_customer_service: 4.9,
    total_brand_ratings: 3102,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
];

export const MOCK_SLIMES: Slime[] = [
  {
    id: "slime-001",
    brand_id: MOCK_BRANDS[0].id,
    name: "Strawberry Shortcake",
    slime_type: "butter",
    colors: ["#F9A8D4", "#FECACA"],
    scent: "Strawberry Vanilla",
    collection_name: "Sweet Dreams",
    is_limited: false,
    image_url: null,
    created_by: "user-001",
    avg_texture: 4.8,
    avg_scent: 4.9,
    avg_sound: 4.2,
    avg_drizzle: 4.5,
    avg_creativity: 4.6,
    avg_sensory_fit: 4.7,
    avg_overall: 4.8,
    total_ratings: 847,
    created_at: "2025-06-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    brand: MOCK_BRANDS[0],
  },
  {
    id: "slime-002",
    brand_id: MOCK_BRANDS[2].id,
    name: "Midnight Galaxy",
    slime_type: "cloud_cream",
    colors: ["#6D28D9", "#1E1B4B", "#7C3AED"],
    scent: "Blackberry Musk",
    collection_name: "Cosmos Collection",
    is_limited: true,
    image_url: null,
    created_by: "user-001",
    avg_texture: 4.9,
    avg_scent: 4.7,
    avg_sound: 4.8,
    avg_drizzle: 4.6,
    avg_creativity: 5.0,
    avg_sensory_fit: 4.9,
    avg_overall: 4.9,
    total_ratings: 1203,
    created_at: "2025-08-15T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    brand: MOCK_BRANDS[2],
  },
  {
    id: "slime-003",
    brand_id: MOCK_BRANDS[1].id,
    name: "Ocean Mist",
    slime_type: "icee",
    colors: ["#BAE6FD", "#7DD3FC", "#0EA5E9"],
    scent: "Sea Salt & Jasmine",
    collection_name: null,
    is_limited: false,
    image_url: null,
    created_by: "user-001",
    avg_texture: 4.6,
    avg_scent: 4.8,
    avg_sound: 4.9,
    avg_drizzle: 4.3,
    avg_creativity: 4.4,
    avg_sensory_fit: 4.7,
    avg_overall: 4.6,
    total_ratings: 562,
    created_at: "2025-09-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    brand: MOCK_BRANDS[1],
  },
  {
    id: "slime-004",
    brand_id: MOCK_BRANDS[0].id,
    name: "Peach Fuzz",
    slime_type: "fluffy",
    colors: ["#FED7AA", "#FDBA74"],
    scent: "Fresh Peach",
    collection_name: "Fuzzy Friends",
    is_limited: false,
    image_url: null,
    created_by: "user-002",
    avg_texture: 4.7,
    avg_scent: 4.9,
    avg_sound: 3.8,
    avg_drizzle: 4.1,
    avg_creativity: 4.3,
    avg_sensory_fit: 4.5,
    avg_overall: 4.5,
    total_ratings: 421,
    created_at: "2025-10-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    brand: MOCK_BRANDS[0],
  },
  {
    id: "slime-005",
    brand_id: MOCK_BRANDS[2].id,
    name: "Watermelon Sugar",
    slime_type: "jelly",
    colors: ["#86EFAC", "#F9A8D4", "#FCA5A5"],
    scent: "Watermelon Candy",
    collection_name: "Summer Haul",
    is_limited: true,
    image_url: null,
    created_by: "user-003",
    avg_texture: 4.5,
    avg_scent: 4.6,
    avg_sound: 4.4,
    avg_drizzle: 4.7,
    avg_creativity: 4.8,
    avg_sensory_fit: 4.6,
    avg_overall: 4.6,
    total_ratings: 334,
    created_at: "2025-07-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    brand: MOCK_BRANDS[2],
  },
  {
    id: "slime-006",
    brand_id: MOCK_BRANDS[1].id,
    name: "Cotton Candy Dream",
    slime_type: "snow_fizz",
    colors: ["#F5D0FE", "#E879F9", "#FAE8FF"],
    scent: "Cotton Candy",
    collection_name: "Carnival",
    is_limited: false,
    image_url: null,
    created_by: "user-001",
    avg_texture: 4.4,
    avg_scent: 4.8,
    avg_sound: 4.6,
    avg_drizzle: 4.2,
    avg_creativity: 4.5,
    avg_sensory_fit: 4.4,
    avg_overall: 4.5,
    total_ratings: 289,
    created_at: "2025-11-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    brand: MOCK_BRANDS[1],
  },
];

export const MOCK_COLLECTION_LOGS: CollectionLog[] = [
  {
    id: "log-001",
    user_id: "user-001",
    slime_id: "slime-001",
    brand_id: MOCK_BRANDS[0].id,
    slime_type: "butter",
    in_collection: true,
    in_wishlist: false,
    rating_texture: 5,
    rating_scent: 5,
    rating_sound: 4,
    rating_drizzle: 5,
    rating_creativity: 4,
    rating_sensory_fit: 5,
    rating_overall: 5,
    notes:
      "Absolutely perfect activation. The scent throw is insane — smells exactly like strawberry shortcake. Butter is so smooth.",
    logged_at: "2026-03-20T14:30:00Z",
    created_at: "2026-03-20T14:30:00Z",
    updated_at: "2026-03-20T14:30:00Z",
    slime: MOCK_SLIMES[0],
    user: MOCK_PROFILE,
  },
  {
    id: "log-002",
    user_id: "user-002",
    slime_id: "slime-002",
    brand_id: MOCK_BRANDS[2].id,
    slime_type: "cloud_cream",
    in_collection: true,
    in_wishlist: false,
    rating_texture: 5,
    rating_scent: 5,
    rating_sound: 5,
    rating_drizzle: 5,
    rating_creativity: 5,
    rating_sensory_fit: 5,
    rating_overall: 5,
    notes:
      "This cloud cream is everything. The crunch from the beads mixed with the cloud texture is next level ASMR.",
    logged_at: "2026-03-22T10:00:00Z",
    created_at: "2026-03-22T10:00:00Z",
    updated_at: "2026-03-22T10:00:00Z",
    slime: MOCK_SLIMES[1],
    user: {
      ...MOCK_PROFILE,
      id: "user-002",
      username: "galaxyslimes",
      full_name: "Aria K.",
    },
  },
  {
    id: "log-003",
    user_id: "user-003",
    slime_id: "slime-003",
    brand_id: MOCK_BRANDS[1].id,
    slime_type: "icee",
    in_collection: true,
    in_wishlist: false,
    rating_texture: 4,
    rating_scent: 5,
    rating_sound: 5,
    rating_drizzle: 4,
    rating_creativity: 4,
    rating_sensory_fit: 5,
    rating_overall: 4,
    notes:
      "That crunch is therapeutic. Perfect ASMR. Could listen to it pop for hours.",
    logged_at: "2026-03-23T16:45:00Z",
    created_at: "2026-03-23T16:45:00Z",
    updated_at: "2026-03-23T16:45:00Z",
    slime: MOCK_SLIMES[2],
    user: {
      ...MOCK_PROFILE,
      id: "user-003",
      username: "slimemom2024",
      full_name: "Tina R.",
    },
  },
];

export const MOCK_DROPS: Drop[] = [
  {
    id: "drop-001",
    brand_id: MOCK_BRANDS[0].id,
    title: "Spring Haul Drop",
    description:
      "12 new scents dropping Friday. Butter, cloud cream, and fluffy. First drop of the season!",
    status: "announced",
    drop_at: "2026-03-28T20:00:00Z",
    announced_by: "user-system",
    created_at: "2026-03-24T00:00:00Z",
    updated_at: "2026-03-24T00:00:00Z",
    brand: MOCK_BRANDS[0],
  },
  {
    id: "drop-002",
    brand_id: MOCK_BRANDS[2].id,
    title: "Cosmos Collection Vol. 2",
    description: "Limited cloud cream galaxy series. Only 200 units per scent.",
    status: "live",
    drop_at: "2026-03-25T18:00:00Z",
    announced_by: "user-system",
    created_at: "2026-03-23T00:00:00Z",
    updated_at: "2026-03-25T18:00:00Z",
    brand: MOCK_BRANDS[2],
  },
  {
    id: "drop-003",
    brand_id: MOCK_BRANDS[1].id,
    title: "Summer Preview",
    description:
      "Early access for members. Tropical-scented icee and jelly line.",
    status: "announced",
    drop_at: "2026-04-04T15:00:00Z",
    announced_by: "user-system",
    created_at: "2026-03-24T00:00:00Z",
    updated_at: "2026-03-24T00:00:00Z",
    brand: MOCK_BRANDS[1],
  },
];

export const MOCK_FEED: ActivityFeedItem[] = [
  {
    id: "feed-001",
    actor_id: "user-002",
    activity_type: "log_created",
    log_id: "log-002",
    slime_id: "slime-002",
    brand_id: MOCK_BRANDS[2].id,
    drop_id: null,
    target_user_id: null,
    metadata: { like_count: 34, comment_count: 7 },
    created_at: "2026-03-22T10:00:00Z",
    actor: {
      ...MOCK_PROFILE,
      id: "user-002",
      username: "galaxyslimes",
      full_name: "Aria K.",
    },
    log: MOCK_COLLECTION_LOGS[1],
    slime: MOCK_SLIMES[1],
    brand: MOCK_BRANDS[2],
  },
  {
    id: "feed-002",
    actor_id: "user-003",
    activity_type: "log_created",
    log_id: "log-003",
    slime_id: "slime-003",
    brand_id: MOCK_BRANDS[1].id,
    drop_id: null,
    target_user_id: null,
    metadata: { like_count: 12, comment_count: 3 },
    created_at: "2026-03-23T16:45:00Z",
    actor: {
      ...MOCK_PROFILE,
      id: "user-003",
      username: "slimemom2024",
      full_name: "Tina R.",
    },
    log: MOCK_COLLECTION_LOGS[2],
    slime: MOCK_SLIMES[2],
    brand: MOCK_BRANDS[1],
  },
  {
    id: "feed-003",
    actor_id: "user-004",
    activity_type: "drop_announced",
    log_id: null,
    slime_id: null,
    brand_id: MOCK_BRANDS[0].id,
    drop_id: "drop-001",
    target_user_id: null,
    metadata: { drop_title: "Spring Haul Drop" },
    created_at: "2026-03-24T09:00:00Z",
    actor: {
      ...MOCK_PROFILE,
      id: "user-004",
      username: "craftyclay",
      full_name: "Marcus P.",
    },
    brand: MOCK_BRANDS[0],
    drop: MOCK_DROPS[0],
  },
  {
    id: "feed-004",
    actor_id: "user-001",
    activity_type: "log_created",
    log_id: "log-001",
    slime_id: "slime-001",
    brand_id: MOCK_BRANDS[0].id,
    drop_id: null,
    target_user_id: null,
    metadata: { like_count: 58, comment_count: 11 },
    created_at: "2026-03-20T14:30:00Z",
    actor: MOCK_PROFILE,
    log: MOCK_COLLECTION_LOGS[0],
    slime: MOCK_SLIMES[0],
    brand: MOCK_BRANDS[0],
  },
];

export const MOCK_COLLECTION_SUMMARY: UserCollectionSummary = {
  user_id: "user-001",
  total_in_collection: 127,
  total_in_wishlist: 43,
  total_rated: 98,
  avg_overall_given: 4.3,
  distinct_brands_tried: 22,
  distinct_types_tried: 14,
};

export const MY_COLLECTION_LOGS: CollectionLog[] = [
  ...MOCK_COLLECTION_LOGS.filter((l) => l.user_id === "user-001"),
  {
    id: "log-004",
    user_id: "user-001",
    slime_id: "slime-004",
    brand_id: MOCK_BRANDS[0].id,
    slime_type: "fluffy",
    in_collection: true,
    in_wishlist: false,
    rating_texture: 5,
    rating_scent: 5,
    rating_sound: 4,
    rating_drizzle: 4,
    rating_creativity: 4,
    rating_sensory_fit: 5,
    rating_overall: 5,
    notes: "Peach scent is dreamy.",
    logged_at: "2026-02-14T12:00:00Z",
    created_at: "2026-02-14T12:00:00Z",
    updated_at: "2026-02-14T12:00:00Z",
    slime: MOCK_SLIMES[3],
    user: MOCK_PROFILE,
  },
  {
    id: "log-005",
    user_id: "user-001",
    slime_id: "slime-005",
    brand_id: MOCK_BRANDS[2].id,
    slime_type: "jelly",
    in_collection: false,
    in_wishlist: true,
    rating_texture: null,
    rating_scent: null,
    rating_sound: null,
    rating_drizzle: null,
    rating_creativity: null,
    rating_sensory_fit: null,
    rating_overall: null,
    notes: null,
    logged_at: "2026-03-10T09:00:00Z",
    created_at: "2026-03-10T09:00:00Z",
    updated_at: "2026-03-10T09:00:00Z",
    slime: MOCK_SLIMES[4],
    user: MOCK_PROFILE,
  },
  {
    id: "log-006",
    user_id: "user-001",
    slime_id: "slime-006",
    brand_id: MOCK_BRANDS[1].id,
    slime_type: "snow_fizz",
    in_collection: true,
    in_wishlist: false,
    rating_texture: 4,
    rating_scent: 5,
    rating_sound: 5,
    rating_drizzle: 4,
    rating_creativity: 4,
    rating_sensory_fit: 4,
    rating_overall: 4,
    notes: "Great fizz on activation.",
    logged_at: "2026-01-30T20:00:00Z",
    created_at: "2026-01-30T20:00:00Z",
    updated_at: "2026-01-30T20:00:00Z",
    slime: MOCK_SLIMES[5],
    user: MOCK_PROFILE,
  },
];
