// apps/web/app/profile/page.tsx
import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import Link from "next/link";
import { formatDistanceToNow } from "date-fns";
import { Pencil } from "lucide-react";
import PageHeader from "@/components/PageHeader";

type CollectionSummary = {
  user_id: string;
  total_in_collection: number | null;
  total_in_wishlist: number | null;
  total_rated: number | null;
  avg_overall_given: number | null;
  distinct_brands_tried: number | null;
  distinct_types_tried: number | null;
};

type RecentLog = {
  id: string;
  created_at: string;
  slime_name: string | null;
  brand_name_raw: string | null;
  slime_type: string | null;
  rating_overall: number | null;
  brands: { name: string | null }[] | null;
};

const TYPE_LABEL: Record<string, string> = {
  butter: "Butter",
  clear: "Clear",
  cloud: "Cloud",
  icee: "Icee",
  fluffy: "Fluffy",
  floam: "Floam",
  snow_fizz: "Snow Fizz",
  thick_and_glossy: "Thick & Glossy",
  jelly: "Jelly",
  beaded: "Beaded",
  clay: "Clay",
  cloud_cream: "Cloud Cream",
  magnetic: "Magnetic",
  thermochromic: "Thermochromic",
  avalanche: "Avalanche",
  slay: "Slay",
};

function resolveDisplayName(username: string): {
  displayName: string;
  handle: string | null;
  isAutoGenerated: boolean;
} {
  if (username.startsWith("user_"))
    return { displayName: "Slimer", handle: username, isAutoGenerated: true };
  return { displayName: username, handle: null, isAutoGenerated: false };
}

function StatTile({
  value,
  label,
  accent,
}: {
  value: string | number | null;
  label: string;
  accent: string;
}) {
  return (
    <div className="bg-slime-card rounded-2xl border border-slime-border p-4 flex flex-col gap-1">
      <p
        className="text-2xl font-black tabular-nums leading-none"
        style={{
          background: accent,
          WebkitBackgroundClip: "text",
          WebkitTextFillColor: "transparent",
        }}
      >
        {value ?? "—"}
      </p>
      <p className="text-xs text-slime-muted font-medium leading-snug">
        {label}
      </p>
    </div>
  );
}

function RecentLogRow({ log }: { log: RecentLog }) {
  const brandName =
    log.brands?.[0]?.name ?? log.brand_name_raw ?? "Unknown brand";
  const typeLabel =
    (log.slime_type && TYPE_LABEL[log.slime_type]) ?? log.slime_type ?? "—";
  const timeAgo = formatDistanceToNow(new Date(log.created_at), {
    addSuffix: true,
  });

  return (
    <li className="flex items-center gap-3 py-3 border-b border-slime-border last:border-0">
      <div
        className="w-9 h-9 rounded-2xl shrink-0 flex items-center justify-center text-lg bg-slime-surface border border-slime-border"
        aria-hidden="true"
      >
        🫧
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold text-slime-text truncate leading-tight">
          {log.slime_name ?? "Untitled slime"}
        </p>
        <p className="text-xs text-slime-muted truncate">
          {brandName} · <span className="text-slime-magenta">{typeLabel}</span>
        </p>
      </div>
      <div className="text-right shrink-0">
        {log.rating_overall ? (
          <p className="text-sm font-bold text-slime-cyan">
            {log.rating_overall}/5
          </p>
        ) : (
          <p className="text-xs text-slime-muted">no rating</p>
        )}
        <time
          className="text-[10px] text-slime-muted"
          dateTime={log.created_at}
        >
          {timeAgo}
        </time>
      </div>
    </li>
  );
}

export default async function ProfilePage() {
  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookies: { get: (name) => cookieStore.get(name)?.value } },
  );

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const [summaryResult, profileResult, recentLogsResult] = await Promise.all([
    supabase
      .from("user_collection_summary")
      .select(
        "user_id, total_in_collection, total_in_wishlist, total_rated, avg_overall_given, distinct_brands_tried, distinct_types_tried",
      )
      .eq("user_id", user.id)
      .maybeSingle(),
    supabase
      .from("profiles")
      .select("username")
      .eq("id", user.id)
      .maybeSingle(),
    supabase
      .from("collection_logs")
      .select(
        "id, created_at, slime_name, brand_name_raw, slime_type, rating_overall, brands ( name )",
      )
      .eq("user_id", user.id)
      .order("created_at", { ascending: false })
      .limit(5),
  ]);

  const summary: CollectionSummary | null = summaryResult.data ?? null;
  const rawUsername = profileResult.data?.username ?? "user_unknown";
  const { displayName, handle, isAutoGenerated } =
    resolveDisplayName(rawUsername);
  const recentLogs: RecentLog[] = recentLogsResult.data ?? [];

  const typeCounts: Record<string, number> = {};
  for (const log of recentLogs) {
    if (log.slime_type)
      typeCounts[log.slime_type] = (typeCounts[log.slime_type] ?? 0) + 1;
  }
  const topType =
    Object.entries(typeCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? null;
  const topTypeLabel = topType ? (TYPE_LABEL[topType] ?? topType) : null;
  const hasErrors =
    summaryResult.error || profileResult.error || recentLogsResult.error;

  return (
    <main className="min-h-screen pb-24 bg-slime-bg">
      <PageHeader />

      <div className="pt-14">
        {/* Profile hero */}
        <div className="px-4 pt-6 pb-6">
          <div className="flex items-center gap-4">
            <div
              className="w-16 h-16 rounded-3xl flex items-center justify-center text-slime-bg text-2xl font-black shadow-glow-green shrink-0"
              style={{
                background: "linear-gradient(135deg, #39FF14, #00F0FF)",
              }}
              aria-hidden="true"
            >
              {displayName.charAt(0).toUpperCase()}
            </div>

            <div className="flex-1 min-w-0">
              <h1 className="text-xl font-black text-slime-cyan leading-tight truncate">
                {displayName}
              </h1>
              <p className="text-sm text-slime-magenta mt-0.5 truncate">
                @{handle ?? rawUsername}
              </p>
              {isAutoGenerated ? (
                <Link
                  href="/settings/profile"
                  className="inline-flex items-center gap-1 text-xs text-slime-accent mt-1 font-medium active:opacity-70 transition-opacity"
                >
                  <Pencil className="w-3 h-3" />
                  Tap to set a custom username
                </Link>
              ) : (
                <Link
                  href="/settings/profile"
                  className="inline-flex items-center gap-1 text-xs text-slime-muted mt-1 font-medium active:opacity-70 transition-opacity hover:text-slime-accent"
                >
                  <Pencil className="w-3 h-3" />
                  Edit profile
                </Link>
              )}
            </div>
          </div>
        </div>

        {hasErrors && (
          <div className="mx-4 mb-4 px-4 py-3 rounded-2xl bg-red-500/10 border border-red-500/30 text-xs text-red-400">
            Some stats couldn't load — try refreshing.
          </div>
        )}

        <section className="px-4 mb-8">
          <h2 className="text-xs text-slime-muted font-semibold uppercase tracking-wider mb-3">
            Collection Stats
          </h2>
          <div className="grid grid-cols-2 gap-3">
            <StatTile
              value={summary?.total_in_collection ?? 0}
              label="Slimes logged"
              accent="#39FF14"
            />
            <StatTile
              value={
                summary?.avg_overall_given != null
                  ? summary.avg_overall_given.toFixed(1)
                  : null
              }
              label="Avg rating given"
              accent="#00F0FF"
            />
            <StatTile
              value={summary?.distinct_brands_tried ?? 0}
              label="Brands tried"
              accent="#FF00E5"
            />
            <StatTile
              value={topTypeLabel ?? summary?.distinct_types_tried ?? 0}
              label={topTypeLabel ? "Fave type (recent)" : "Types tried"}
              accent="#39FF14"
            />
          </div>
        </section>

        <section className="px-4">
          <h2 className="text-xs text-slime-muted font-semibold uppercase tracking-wider mb-3">
            Recent Activity
          </h2>
          <div className="bg-slime-card rounded-2xl border border-slime-border px-4">
            {recentLogs.length === 0 ? (
              <div className="py-10 text-center text-slime-muted text-sm">
                No logs yet — tap{" "}
                <span className="font-semibold text-slime-accent">+ Log</span>{" "}
                to add your first slime.
              </div>
            ) : (
              <ul role="list">
                {recentLogs.map((log) => (
                  <RecentLogRow key={log.id} log={log} />
                ))}
              </ul>
            )}
          </div>
        </section>
      </div>
    </main>
  );
}
