// apps/web/app/profile/page.tsx
import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import Link from "next/link";
import PageHeader from "@/components/PageHeader";
import PageWrapper from "@/components/PageWrapper";
import FloatingPills from "@/components/FloatingPills";
import ProfileFeaturedSection from "@/components/profile/ProfileFeaturedSection";
// [Change: replaced local TYPE_LABEL constant with SLIME_TYPE_LABELS from @/lib/types]
import { SLIME_TYPE_LABELS, type SlimeType } from "@/lib/types";

// ─── Types ─────────────────────────────────────────────────────────────────────

type CollectionSummary = {
  user_id: string;
  total_in_collection: number | null;
  total_in_wishlist: number | null;
  total_rated: number | null;
  avg_overall_given: number | null;
  distinct_brands_tried: number | null;
  distinct_types_tried: number | null;
};

type RecentLog = {
  id: string;
  created_at: string;
  slime_name: string | null;
  brand_name_raw: string | null;
  slime_type: string | null;
  rating_overall: number | null;
  brands: { name: string | null }[] | null;
};

// [Change: types for featured slimes data passed to ProfileFeaturedSection]
type FeaturedLog = {
  id: string;
  slime_name: string | null;
  brand_name_raw: string | null;
  slime_type: string | null;
  rating_overall: number | null;
  image_url: string | null;
  colors: string[] | null;
};

type CandidateLog = {
  id: string;
  slime_name: string | null;
  brand_name_raw: string | null;
  slime_type: string | null;
  rating_overall: number | null;
  image_url: string | null;
  colors: string[] | null;
};

// ─── Helpers ───────────────────────────────────────────────────────────────────

function resolveDisplayName(username: string): {
  displayName: string;
  handle: string | null;
  isAutoGenerated: boolean;
} {
  if (username.startsWith("user_"))
    return { displayName: "Slimer", handle: username, isAutoGenerated: true };
  return { displayName: username, handle: null, isAutoGenerated: false };
}

// [Fix B] Inline relative time — copied verbatim from apps/web/app/users/[username]/page.tsx
// so the owner profile's Recent logs cards show the same "Xh ago" / "Xd ago" format as the
// public profile. Absolute rule compliance: no date-fns, inline Intl only.
function formatRelativeTime(isoString: string): string {
  const diffMs = Date.now() - new Date(isoString).getTime();
  const diffMins = Math.floor(diffMs / 1000 / 60);
  if (diffMins < 1) return "just now";
  if (diffMins < 60) return `${diffMins}m ago`;
  const diffHours = Math.floor(diffMins / 60);
  if (diffHours < 24) return `${diffHours}h ago`;
  const diffDays = Math.floor(diffHours / 24);
  if (diffDays < 30) return `${diffDays}d ago`;
  const diffMonths = Math.floor(diffDays / 30);
  if (diffMonths < 12) return `${diffMonths}mo ago`;
  return `${Math.floor(diffMonths / 12)}y ago`;
}

// ─── Sub-components ────────────────────────────────────────────────────────────

// [Fix B] Stars component — copied verbatim from apps/web/app/users/[username]/page.tsx
// for visual parity on the Recent logs card bottom-row.
function Stars({ rating }: { rating: number | null }) {
  if (!rating) return <span className="text-xs text-slime-muted">—</span>;
  return (
    <span
      className="flex items-center gap-0.5"
      aria-label={`${rating} out of 5`}
    >
      {[1, 2, 3, 4, 5].map((n) => (
        <svg
          key={n}
          width="12"
          height="12"
          viewBox="0 0 24 24"
          fill={n <= rating ? "#39FF14" : "rgba(57,255,20,0.15)"}
          aria-hidden="true"
        >
          <polygon points="12,2 15.09,8.26 22,9.27 17,14.14 18.18,21.02 12,17.77 5.82,21.02 7,14.14 2,9.27 8.91,8.26" />
        </svg>
      ))}
    </span>
  );
}

// [Fix A] StatTile rewritten for horizontal-scroll layout:
//   - Outer container adds `snap-start shrink-0 w-36` so tiles behave as fixed-width
//     snap targets inside the scroll container.
//   - Number variant now uses a solid color via `style.color`, not gradient-text.
//     The `accent` prop takes a plain hex string (e.g. "#39FF14") rather than a
//     gradient definition.
//   - Pill variant scales up to text-base / px-3 py-1 / font-black / leading-tight
//     so the "Fav type" tile no longer looks underweight next to the 2xl numerals.
//   - Label styling and empty-state em-dash for pill variant are unchanged.
// Function signature is preserved.
function StatTile({
  value,
  label,
  accent,
  variant = "number",
}: {
  value: string | number | null;
  label: string;
  accent: string;
  variant?: "number" | "pill";
}) {
  return (
    <div
      className="snap-start shrink-0 w-36 rounded-2xl p-4 flex flex-col gap-1 min-h-20"
      style={{
        background: "rgba(45,10,78,0.3)",
        border: "1px solid rgba(45,10,78,0.7)",
        boxShadow: "inset 0 0 16px rgba(45,10,78,0.2)",
      }}
    >
      {variant === "pill" ? (
        value != null && value !== "" ? (
          // [Fix A] Magenta pill — scaled up from text-xs / px-2 py-0.5 to
          // text-base / px-3 py-1 / font-black / leading-tight.
          <span
            className="text-base font-black px-3 py-1 rounded-full self-start leading-tight"
            style={{
              background: "rgba(255,0,229,0.12)",
              color: "#FF00E5",
              border: "1px solid rgba(255,0,229,0.3)",
            }}
          >
            {value}
          </span>
        ) : (
          <span className="text-sm text-slime-muted leading-none">—</span>
        )
      ) : (
        // [Fix A] Solid-color numeral — replaces prior gradient background-clip.
        // `accent` is a flat hex color string like "#39FF14", "#00F0FF", "#FF00E5".
        <p
          className="text-2xl font-black tabular-nums leading-none"
          style={{ color: accent }}
        >
          {value ?? "—"}
        </p>
      )}
      <p className="text-xs text-slime-muted font-medium leading-snug">
        {label}
      </p>
    </div>
  );
}

// [Fix B] RecentLogRow deleted — replaced with inline card markup in the page body
// that mirrors apps/web/app/users/[username]/page.tsx Recent logs.

// ─── Page ──────────────────────────────────────────────────────────────────────

export default async function ProfilePage() {
  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookies: { get: (name) => cookieStore.get(name)?.value } },
  );

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  // [Fix 39] Extended profiles select to include instagram_handle, tiktok_handle, shop_url
  // so the owner profile can render the same social links row the public profile shows.
  // [Fix C] Recent logs limit bumped from 5 to 6 to match public profile.
  const [summaryResult, profileResult, recentLogsResult, allLogsResult] =
    await Promise.all([
      supabase
        .from("user_collection_summary")
        .select(
          "user_id, total_in_collection, total_in_wishlist, total_rated, avg_overall_given, distinct_brands_tried, distinct_types_tried",
        )
        .eq("user_id", user.id)
        .maybeSingle(),
      supabase
        .from("profiles")
        .select(
          "username, avatar_url, featured_log_ids, instagram_handle, tiktok_handle, shop_url",
        )
        .eq("id", user.id)
        .maybeSingle(),
      supabase
        .from("collection_logs")
        .select(
          "id, created_at, slime_name, brand_name_raw, slime_type, rating_overall, brands ( name )",
        )
        .eq("user_id", user.id)
        .order("created_at", { ascending: false })
        // [Fix C] Bumped 5 → 6 to match public profile. Note we intentionally do NOT
        // filter by is_public here — owners see their own private logs on their own profile.
        .limit(6),
      // [Change: fetch all in_collection logs as candidates for the editor]
      supabase
        .from("collection_logs")
        .select(
          "id, slime_name, brand_name_raw, slime_type, rating_overall, image_url, colors",
        )
        .eq("user_id", user.id)
        .eq("in_collection", true)
        .order("created_at", { ascending: false }),
    ]);

  const summary: CollectionSummary | null = summaryResult.data ?? null;
  const rawUsername = profileResult.data?.username ?? "user_unknown";
  const avatarUrl = profileResult.data?.avatar_url ?? null;
  // [Fix 39] Destructure social handles from the profile row
  const instagramHandle = profileResult.data?.instagram_handle ?? null;
  const tiktokHandle = profileResult.data?.tiktok_handle ?? null;
  const shopUrl = profileResult.data?.shop_url ?? null;
  const { displayName, handle, isAutoGenerated } =
    resolveDisplayName(rawUsername);
  const recentLogs: RecentLog[] = recentLogsResult.data ?? [];
  const allCollectionLogs: CandidateLog[] = (allLogsResult.data ??
    []) as CandidateLog[];

  // [Fix 39] Conditional render flag for the social links row
  const hasSocialLinks = !!instagramHandle || !!tiktokHandle || !!shopUrl;

  // [Change: resolve featured_log_ids and fetch the actual log rows in order]
  const rawFeaturedIds: string[] = profileResult.data?.featured_log_ids ?? [];
  const featuredIds = rawFeaturedIds.filter((id): id is string => !!id);
  let featuredLogs: FeaturedLog[] = [];

  if (featuredIds.length > 0) {
    const { data: featuredData } = await supabase
      .from("collection_logs")
      .select(
        "id, slime_name, brand_name_raw, slime_type, rating_overall, image_url, colors",
      )
      .in("id", featuredIds);

    // Preserve the order of featuredIds
    const byId: Record<string, FeaturedLog> = {};
    for (const row of featuredData ?? []) {
      byId[row.id] = row as FeaturedLog;
    }
    featuredLogs = featuredIds.map((id) => byId[id]).filter(Boolean);
  }

  // [Change: use SLIME_TYPE_LABELS for fave type computation]
  const typeCounts: Record<string, number> = {};
  for (const log of recentLogs) {
    if (log.slime_type)
      typeCounts[log.slime_type] = (typeCounts[log.slime_type] ?? 0) + 1;
  }
  const topType =
    Object.entries(typeCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? null;
  const topTypeLabel = topType
    ? (SLIME_TYPE_LABELS[topType as SlimeType] ?? topType)
    : null;

  const hasErrors =
    summaryResult.error ||
    profileResult.error ||
    recentLogsResult.error ||
    allLogsResult.error;

  // [Fix C] Wishlist link visibility — only render when we have summary data AND
  // a non-zero wishlist count. Null or 0 hides the link entirely, per spec.
  const showWishlistLink =
    summary != null &&
    summary.total_in_wishlist != null &&
    summary.total_in_wishlist > 0;

  return (
    <PageWrapper dots glow="cyan">
      {/* [Fix A] Hide horizontal scrollbar on WebKit and Firefox for the stats
          scroller. Scoped to .scrollbar-hide so it doesn't leak to the page. */}
      <style>{`
        .scrollbar-hide::-webkit-scrollbar { display: none; }
        .scrollbar-hide { -ms-overflow-style: none; scrollbar-width: none; }
      `}</style>

      <PageHeader />

      <div className="pt-14">
        {/* Profile hero with floating pills */}
        <div className="relative px-4 pt-8 pb-6 overflow-hidden">
          <FloatingPills area="section" density="low" zIndex={0} />

          <div className="relative z-10 flex items-center gap-4">
            {/* Holographic avatar ring */}
            <div
              className="p-0.5 rounded-3xl shrink-0"
              style={{
                background:
                  "linear-gradient(135deg, #39FF14, #00F0FF, #FF00E5)",
              }}
            >
              <div className="w-16 h-16 rounded-3xl overflow-hidden bg-slime-bg flex items-center justify-center">
                {avatarUrl ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={avatarUrl}
                    alt="Avatar"
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <div
                    className="w-full h-full flex items-center justify-center text-slime-bg text-2xl font-black"
                    style={{
                      background: "linear-gradient(135deg, #39FF14, #00F0FF)",
                    }}
                    aria-hidden="true"
                  >
                    {displayName.charAt(0).toUpperCase()}
                  </div>
                )}
              </div>
            </div>

            <div className="flex-1 min-w-0">
              <h1 className="text-xl font-black text-slime-cyan leading-tight truncate">
                {displayName}
              </h1>
              <p className="text-sm text-slime-magenta mt-0.5 truncate">
                @{handle ?? rawUsername}
              </p>
              {isAutoGenerated ? (
                <Link
                  href="/settings/profile"
                  className="inline-flex items-center gap-1 text-xs text-slime-accent mt-1 font-medium active:opacity-70 transition-opacity"
                >
                  {/* Inline pencil SVG — no lucide import */}
                  <svg
                    width="14"
                    height="14"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                  </svg>
                  Tap to set a custom username
                </Link>
              ) : (
                <Link
                  href="/settings/profile"
                  className="inline-flex items-center gap-1 text-xs text-slime-muted mt-1 font-medium active:opacity-70 transition-opacity hover:text-slime-accent"
                >
                  <svg
                    width="14"
                    height="14"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                  </svg>
                  Edit profile
                </Link>
              )}
            </div>
          </div>

          {/* [Fix 39] Social links row — icon-only 36x36 circular pill buttons.
              Visual treatment copied verbatim from apps/web/app/users/[username]/page.tsx
              (rgba(45,10,78,0.25) bg, rgba(45,10,78,0.7) border, cyan #00F0FF icon,
              hover → slime-accent). SVGs bumped to 18x18 to match Fix 37.
              Row sits below the main avatar/name/edit block but still inside the hero
              container so it reads as part of the profile header. Renders nothing
              when no social links are set. */}
          {hasSocialLinks && (
            <div className="relative z-10 flex items-center gap-2 mt-3">
              {instagramHandle && (
                <a
                  href={`https://instagram.com/${instagramHandle}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={`Instagram profile: @${instagramHandle}`}
                  className="flex items-center justify-center w-9 h-9 rounded-full transition-colors hover:text-slime-accent"
                  style={{
                    background: "rgba(45,10,78,0.25)",
                    border: "1px solid rgba(45,10,78,0.7)",
                    color: "#00F0FF",
                  }}
                >
                  <svg
                    width="18"
                    height="18"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    aria-hidden="true"
                  >
                    <rect x="2" y="2" width="20" height="20" rx="5" ry="5" />
                    <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
                    <line x1="17.5" y1="6.5" x2="17.51" y2="6.5" />
                  </svg>
                </a>
              )}
              {tiktokHandle && (
                <a
                  href={`https://www.tiktok.com/@${tiktokHandle}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={`TikTok profile: @${tiktokHandle}`}
                  className="flex items-center justify-center w-9 h-9 rounded-full transition-colors hover:text-slime-accent"
                  style={{
                    background: "rgba(45,10,78,0.25)",
                    border: "1px solid rgba(45,10,78,0.7)",
                    color: "#00F0FF",
                  }}
                >
                  <svg
                    width="18"
                    height="18"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    aria-hidden="true"
                  >
                    <path d="M9 18V5l12-2v13" />
                    <circle cx="6" cy="18" r="3" />
                    <circle cx="18" cy="16" r="3" />
                  </svg>
                </a>
              )}
              {shopUrl && (
                <a
                  href={shopUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={`Shop: ${shopUrl}`}
                  className="flex items-center justify-center w-9 h-9 rounded-full transition-colors hover:text-slime-accent"
                  style={{
                    background: "rgba(45,10,78,0.25)",
                    border: "1px solid rgba(45,10,78,0.7)",
                    color: "#00F0FF",
                  }}
                >
                  <svg
                    width="18"
                    height="18"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    aria-hidden="true"
                  >
                    <path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z" />
                    <line x1="3" y1="6" x2="21" y2="6" />
                    <path d="M16 10a4 4 0 0 1-8 0" />
                  </svg>
                </a>
              )}
            </div>
          )}
        </div>

        {hasErrors && (
          <div className="mx-4 mb-4 px-4 py-3 rounded-2xl bg-red-500/10 border border-red-500/30 text-xs text-red-400">
            Some stats couldn&apos;t load — try refreshing.
          </div>
        )}

        {/* [Change: Featured Slimes section — client component, above stats, omitted if empty] */}
        <ProfileFeaturedSection
          initialFeaturedLogs={featuredLogs}
          initialFeaturedIds={featuredIds}
          allCollectionLogs={allCollectionLogs}
          userId={user.id}
        />

        {/* [Fix A] Stats — horizontal scroll container replaces the previous 2x2 grid.
            [Fix C] Heading switches from `section-label` to the public-profile class
            (text-xs text-slime-muted font-semibold uppercase tracking-wider) for
            visual parity across profile pages. Wording "Collection Stats" unchanged. */}
        <section className="px-4 mb-8">
          <h2 className="text-xs text-slime-muted font-semibold uppercase tracking-wider mb-3">
            Collection Stats
          </h2>
          {/* [Fix A] The scroller uses negative horizontal margins + matching padding
              so the scrollable area reaches the page edges visually, while keeping
              the tiles aligned with the surrounding px-4 content. snap-x +
              snap-mandatory + w-max on the inner flex row create the snap behavior. */}
          <div className="overflow-x-auto -mx-4 px-4 pb-2 snap-x snap-mandatory scrollbar-hide">
            <div className="flex gap-3 w-max">
              <StatTile
                value={summary?.total_in_collection ?? 0}
                label="Slimes logged"
                accent="#39FF14"
              />
              <StatTile
                value={
                  summary?.avg_overall_given != null
                    ? summary.avg_overall_given.toFixed(1)
                    : null
                }
                label="Avg rating given"
                accent="#00F0FF"
              />
              <StatTile
                value={summary?.distinct_brands_tried ?? 0}
                label="Brands tried"
                accent="#FF00E5"
              />
              {/* [Fix A] Fav type tile: pill variant when a top type exists, number
                  variant otherwise. Accent color is neon green for the number
                  fallback so the tile reads as a count, not a label. */}
              <StatTile
                value={topTypeLabel ?? summary?.distinct_types_tried ?? 0}
                label={topTypeLabel ? "Fave type (recent)" : "Types tried"}
                accent="#39FF14"
                variant={topTypeLabel ? "pill" : "number"}
              />
            </div>
          </div>
        </section>

        {/* [Fix B][Fix C] Recent logs — card layout matching public profile.
            - Heading renamed "Recent Activity" → "Recent logs" with the public
              profile heading class.
            - Wishlist link moved here as a right-aligned CTA next to the heading
              (hidden when count is 0 or null).
            - Cards wrap in Link to /slimes/{id} so tapping a log opens the detail
              view. The outer purple container that used to wrap the row list has
              been removed — cards stand alone in a flex column with gap-2.5. */}
        <section className="px-4 pb-24">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-xs text-slime-muted font-semibold uppercase tracking-wider">
              Recent logs
            </h2>
            {showWishlistLink && (
              <Link
                href="/wishlist"
                className="inline-flex items-center gap-1 text-xs font-semibold transition-opacity active:opacity-70"
                style={{ color: "#CC44FF", textDecoration: "none" }}
              >
                <svg
                  width="12"
                  height="12"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  aria-hidden="true"
                >
                  <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z" />
                </svg>
                {summary?.total_in_wishlist} wishlisted
              </Link>
            )}
          </div>

          {recentLogs.length === 0 ? (
            // [Fix B] Empty state — copied from public profile for visual consistency.
            // Wording tweaked to nudge the owner toward the + Log action since this is
            // their own profile, not someone else's.
            <div className="flex flex-col items-center justify-center py-12 gap-3 text-center">
              <div
                className="w-14 h-14 rounded-full flex items-center justify-center"
                style={{
                  background: "rgba(45,10,78,0.25)",
                  border: "1px solid rgba(45,10,78,0.7)",
                }}
              >
                <svg
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="rgba(255,255,255,0.25)"
                  strokeWidth="1.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  aria-hidden="true"
                >
                  <circle cx="12" cy="12" r="10" />
                  <circle
                    cx="8"
                    cy="9"
                    r="1.5"
                    fill="rgba(255,255,255,0.25)"
                    stroke="none"
                  />
                  <circle
                    cx="15"
                    cy="9"
                    r="1.5"
                    fill="rgba(255,255,255,0.25)"
                    stroke="none"
                  />
                  <path d="M8 15s1.5 2 4 2 4-2 4-2" />
                </svg>
              </div>
              <p className="text-sm text-slime-muted">
                No logs yet — tap{" "}
                <span className="font-semibold text-slime-accent">+ Log</span>{" "}
                to add your first slime
              </p>
            </div>
          ) : (
            <div className="flex flex-col gap-2.5">
              {recentLogs.map((log) => {
                const brandName =
                  log.brands?.[0]?.name ??
                  log.brand_name_raw ??
                  "Unknown brand";
                // [Change: use SLIME_TYPE_LABELS instead of local TYPE_LABEL]
                const typeLabel =
                  (log.slime_type &&
                    SLIME_TYPE_LABELS[log.slime_type as SlimeType]) ??
                  log.slime_type ??
                  null;
                return (
                  <Link
                    key={log.id}
                    href={`/slimes/${log.id}`}
                    className="block group"
                  >
                    {/* [Fix B] Card markup copied from public profile. Border lives
                        on the Tailwind className (not inline style) so the
                        group-hover:border-slime-accent/30 rule can actually override
                        it. Inline style retains only the background. */}
                    <article
                      className="rounded-2xl p-4 border border-[rgba(45,10,78,0.7)] transition-all duration-100 group-hover:border-slime-accent/30 group-active:scale-[0.98]"
                      style={{ background: "rgba(45,10,78,0.25)" }}
                    >
                      <div className="flex items-start justify-between gap-2">
                        <div className="min-w-0 flex-1">
                          <p className="font-semibold text-slime-text text-sm truncate">
                            {log.slime_name ?? "Untitled slime"}
                          </p>
                          <p className="text-xs text-slime-muted truncate mt-0.5">
                            {brandName}
                          </p>
                        </div>
                        {typeLabel && log.slime_type && (
                          <span
                            className="shrink-0 text-xs font-bold px-2 py-0.5 rounded-full"
                            style={{
                              background: "rgba(255,0,229,0.12)",
                              color: "#FF00E5",
                              border: "1px solid rgba(255,0,229,0.3)",
                            }}
                          >
                            {typeLabel}
                          </span>
                        )}
                      </div>
                      <div className="flex items-center justify-between mt-2">
                        <Stars rating={log.rating_overall} />
                        <time
                          className="text-[11px] text-slime-muted"
                          dateTime={log.created_at}
                        >
                          {formatRelativeTime(log.created_at)}
                        </time>
                      </div>
                    </article>
                  </Link>
                );
              })}
            </div>
          )}
        </section>
      </div>
    </PageWrapper>
  );
}
