// apps/web/app/profile/page.tsx
// Updated: uses PageHeader, removes inline header, adds pt-14.

import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import Link from "next/link";
import { formatDistanceToNow } from "date-fns";
import PageHeader from "@/components/PageHeader";

// ─── Types ────────────────────────────────────────────────────────────────────

type CollectionSummary = {
  user_id: string;
  total_in_collection: number | null;
  total_in_wishlist: number | null;
  total_rated: number | null;
  avg_overall_given: number | null;
  distinct_brands_tried: number | null;
  distinct_types_tried: number | null;
};

type RecentLog = {
  id: string;
  created_at: string;
  slime_name: string | null;
  brand_name_raw: string | null;
  slime_type: string | null;
  rating_overall: number | null;
  brands: { name: string | null }[] | null;
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

const TYPE_LABEL: Record<string, string> = {
  butter: "Butter",
  clear: "Clear",
  cloud: "Cloud",
  icee: "Icee",
  fluffy: "Fluffy",
  floam: "Floam",
  snow_fizz: "Snow Fizz",
  thick_and_glossy: "Thick & Glossy",
  jelly: "Jelly",
  beaded: "Beaded",
  clay: "Clay",
  cloud_cream: "Cloud Cream",
  magnetic: "Magnetic",
  thermochromic: "Thermochromic",
  avalanche: "Avalanche",
  slay: "Slay",
};

function resolveDisplayName(username: string): {
  displayName: string;
  handle: string | null;
  isAutoGenerated: boolean;
} {
  if (username.startsWith("user_")) {
    return { displayName: "Slimer", handle: username, isAutoGenerated: true };
  }
  return { displayName: username, handle: null, isAutoGenerated: false };
}

function StatTile({
  value,
  label,
  accent,
}: {
  value: string | number | null;
  label: string;
  accent: string;
}) {
  return (
    <div className="bg-white rounded-2xl border border-pink-50 shadow-sm p-4 flex flex-col gap-1">
      <p
        className="text-2xl font-black tabular-nums leading-none"
        style={{
          background: accent,
          WebkitBackgroundClip: "text",
          WebkitTextFillColor: "transparent",
        }}
      >
        {value ?? "—"}
      </p>
      <p className="text-xs text-gray-400 font-medium leading-snug">{label}</p>
    </div>
  );
}

function RecentLogRow({ log }: { log: RecentLog }) {
  const brandName =
    log.brands?.[0]?.name ?? log.brand_name_raw ?? "Unknown brand";
  const typeLabel =
    (log.slime_type && TYPE_LABEL[log.slime_type]) ?? log.slime_type ?? "—";
  const timeAgo = formatDistanceToNow(new Date(log.created_at), {
    addSuffix: true,
  });

  return (
    <li className="flex items-center gap-3 py-3 border-b border-pink-50 last:border-0">
      <div
        className="w-9 h-9 rounded-2xl shrink-0 flex items-center justify-center text-lg"
        style={{ background: "linear-gradient(135deg, #fce7f3, #f3e8ff)" }}
        aria-hidden="true"
      >
        🫧
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm font-semibold text-gray-900 truncate leading-tight">
          {log.slime_name ?? "Untitled slime"}
        </p>
        <p className="text-xs text-gray-400 truncate">
          {brandName} · {typeLabel}
        </p>
      </div>
      <div className="text-right shrink-0">
        {log.rating_overall ? (
          <p className="text-sm font-bold text-pink-500">
            {log.rating_overall}/5
          </p>
        ) : (
          <p className="text-xs text-gray-300">no rating</p>
        )}
        <time className="text-[10px] text-gray-300" dateTime={log.created_at}>
          {timeAgo}
        </time>
      </div>
    </li>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default async function ProfilePage() {
  const cookieStore = await cookies();

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name) {
          return cookieStore.get(name)?.value;
        },
      },
    },
  );

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) redirect("/login");

  const [summaryResult, profileResult, recentLogsResult] = await Promise.all([
    supabase
      .from("user_collection_summary")
      .select(
        "user_id, total_in_collection, total_in_wishlist, total_rated, avg_overall_given, distinct_brands_tried, distinct_types_tried",
      )
      .eq("user_id", user.id)
      .maybeSingle(),

    supabase
      .from("profiles")
      .select("username")
      .eq("id", user.id)
      .maybeSingle(),

    supabase
      .from("collection_logs")
      .select(
        "id, created_at, slime_name, brand_name_raw, slime_type, rating_overall, brands ( name )",
      )
      .eq("user_id", user.id)
      .order("created_at", { ascending: false })
      .limit(5),
  ]);

  const summary: CollectionSummary | null = summaryResult.data ?? null;
  const rawUsername = profileResult.data?.username ?? "user_unknown";
  const { displayName, handle, isAutoGenerated } =
    resolveDisplayName(rawUsername);

  const recentLogs: RecentLog[] = recentLogsResult.data ?? [];

  const typeCounts: Record<string, number> = {};
  for (const log of recentLogs) {
    if (log.slime_type)
      typeCounts[log.slime_type] = (typeCounts[log.slime_type] ?? 0) + 1;
  }
  const topType =
    Object.entries(typeCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? null;
  const topTypeLabel = topType ? (TYPE_LABEL[topType] ?? topType) : null;

  const hasErrors =
    summaryResult.error || profileResult.error || recentLogsResult.error;

  return (
    <main
      className="min-h-screen pb-24"
      style={{
        background: "linear-gradient(160deg, #fdf2f8 0%, #faf5ff 100%)",
      }}
    >
      {/* Fixed page header */}
      <PageHeader />

      {/* Content — push below fixed header */}
      <div className="pt-14">
        {/* Profile hero */}
        <div className="px-4 pt-6 pb-6">
          <div className="flex items-center gap-4">
            <div
              className="w-16 h-16 rounded-3xl flex items-center justify-center text-white text-2xl font-black shadow-md shrink-0"
              style={{
                background: "linear-gradient(135deg, #f472b6, #a855f7)",
              }}
              aria-hidden="true"
            >
              {displayName.charAt(0).toUpperCase()}
            </div>

            <div className="flex-1 min-w-0">
              <h1 className="text-xl font-black text-gray-900 leading-tight truncate">
                {displayName}
              </h1>

              <p className="text-sm text-gray-400 mt-0.5 truncate">
                @{handle ?? rawUsername}
              </p>

              {isAutoGenerated ? (
                <Link
                  href="/settings/profile"
                  className="inline-block text-xs text-pink-400 mt-1 font-medium active:opacity-70 transition-opacity"
                >
                  ✏️ Tap to set a custom username
                </Link>
              ) : (
                <Link
                  href="/settings/profile"
                  className="inline-block text-xs text-gray-400 mt-1 font-medium active:opacity-70 transition-opacity"
                >
                  ✏️ Edit profile
                </Link>
              )}
            </div>
          </div>
        </div>

        {hasErrors && (
          <div className="mx-4 mb-4 px-4 py-3 rounded-2xl bg-red-50 border border-red-100 text-xs text-red-500">
            Some stats couldn't load — try refreshing.
          </div>
        )}

        {/* Stats */}
        <section className="px-4 mb-8">
          <h2 className="text-xs text-gray-400 font-semibold uppercase tracking-wider mb-3">
            Collection Stats
          </h2>
          <div className="grid grid-cols-2 gap-3">
            <StatTile
              value={summary?.total_in_collection ?? 0}
              label="Slimes logged"
              accent="linear-gradient(90deg, #ec4899, #a855f7)"
            />
            <StatTile
              value={
                summary?.avg_overall_given != null
                  ? summary.avg_overall_given.toFixed(1)
                  : null
              }
              label="Avg rating given"
              accent="linear-gradient(90deg, #f59e0b, #ec4899)"
            />
            <StatTile
              value={summary?.distinct_brands_tried ?? 0}
              label="Brands tried"
              accent="linear-gradient(90deg, #a855f7, #6366f1)"
            />
            <StatTile
              value={topTypeLabel ?? summary?.distinct_types_tried ?? 0}
              label={topTypeLabel ? "Fave type (recent)" : "Types tried"}
              accent="linear-gradient(90deg, #ec4899, #f97316)"
            />
          </div>
        </section>

        {/* Recent activity */}
        <section className="px-4">
          <h2 className="text-xs text-gray-400 font-semibold uppercase tracking-wider mb-3">
            Recent Activity
          </h2>
          <div className="bg-white rounded-2xl border border-pink-50 shadow-sm px-4">
            {recentLogs.length === 0 ? (
              <div className="py-10 text-center text-gray-400 text-sm">
                No logs yet — head to{" "}
                <span
                  className="font-semibold"
                  style={{
                    background: "linear-gradient(90deg, #ec4899, #a855f7)",
                    WebkitBackgroundClip: "text",
                    WebkitTextFillColor: "transparent",
                  }}
                >
                  /log
                </span>{" "}
                to add your first slime.
              </div>
            ) : (
              <ul role="list">
                {recentLogs.map((log) => (
                  <RecentLogRow key={log.id} log={log} />
                ))}
              </ul>
            )}
          </div>
        </section>
      </div>
    </main>
  );
}
