-- Migration: 20260406000023_seed_brands_final
-- Table altered: brands
-- Reason: Seed 202 slime brands from Cowork final research database

INSERT INTO public.brands (slug, name, shop_url, instagram_handle, verification_tier)
VALUES
  ('glitter-slimes', 'Glitter Slimes', 'glitterslimes.com', '@glitter.slimes', 'community'),
  ('karina-garcia-craft-city', 'Karina Garcia / Craft City', NULL, '@karinakgarcia', 'community'),
  ('peachybbies', 'Peachybbies', 'peachybbies.com', '@peachybbies', 'community'),
  ('snoopslimes', 'Snoopslimes', 'snoopslimes.co', '@snoopslimes', 'community'),
  ('craftyslimecreator', 'CraftySlimeCreator', NULL, '@craftyslimecreator', 'community'),
  ('fireflyslime', 'Fireflyslime', 'fireflyslime.com', '@fireflyslime', 'community'),
  ('kawaii-slime-company', 'Kawaii Slime Company', 'kawaiislimecompany.com', '@kawaii.slime.company', 'community'),
  ('macarons-slime', 'Macarons Slime', 'macaronsslime.com', '@macaronsslime', 'community'),
  ('nichole-jacklyne', 'Nichole Jacklyne', NULL, '@nicholejacklyne', 'community'),
  ('piggy-slimes', 'Piggy Slimes', NULL, '@piggysslime', 'community'),
  ('scented-slime-by-amy', 'Scented Slime by Amy', NULL, '@scentedslimebyamy', 'community'),
  ('sliimeyhoney', 'Sliimeyhoney', 'sliimeyhoney.com', '@sliimeyhoney', 'community'),
  ('slimeatory', 'Slimeatory', 'slimeatory.com', '@slimeatoryofficial', 'community'),
  ('slimeglitterz', 'Slimeglitterz', 'slimeglitterz.com', '@slimeglitterz', 'community'),
  ('amma-slimes', 'Amma Slimes', NULL, '@ammaslimes', 'community'),
  ('artistic-rainbow-slime', 'Artistic Rainbow Slime', 'artisticrainbow.com', NULL, 'community'),
  ('artistic-slimez', 'Artistic Slimez', 'artisticslimez.com', '@ArtisticSlimez', 'community'),
  ('bleu-slime', 'Bleu Slime', NULL, '@bleauslime', 'community'),
  ('cloud-nine-slimes', 'Cloud Nine Slimes', NULL, '@cloudnineslimess_', 'community'),
  ('cornwithslime', 'Cornwithslime', 'cornwithslime.com', NULL, 'community'),
  ('db-slime', 'D&B Slime', NULL, NULL, 'community'),
  ('dreamglow-slime', 'Dreamglow Slime', NULL, '@dreamglowslime', 'community'),
  ('emiko-ffujio', 'Emiko Ffujio', NULL, NULL, 'community'),
  ('hoshimi-slimes', 'Hoshimi Slimes', 'hoshimislimes.com', NULL, 'community'),
  ('julia-slime', 'Julia Slime', NULL, NULL, 'community'),
  ('lemons-and-slimes', 'Lemons and Slimes', 'lemonsandslimes.com', NULL, 'community'),
  ('library-of-slime-bookshelf-slimes', 'Library of Slime / Bookshelf Slimes', 'thelibraryofslime.com', NULL, 'community'),
  ('pink-sugar-slime', 'Pink Sugar Slime', NULL, '@pinksugarslime', 'community'),
  ('pinksugarslimey', 'PinkSugarSlimey', 'pinksugarslimey.com', NULL, 'community'),
  ('retro-slime-company', 'Retro Slime Company', 'retroslimecompany.com', NULL, 'community'),
  ('slime-fantasies', 'Slime Fantasies', 'slimefantasies.com', NULL, 'community'),
  ('slime-new-york', 'Slime New York', 'slimenewyork.com', NULL, 'community'),
  ('slime-shop-cafe', 'Slime Shop Cafe', 'slimeshopcafe.com', NULL, 'community'),
  ('slimeowy', 'Slimeowy', 'slimeowy.com', '@slimeowy', 'community'),
  ('slimes-by-grace', 'Slimes by Grace', NULL, NULL, 'community'),
  ('snoop-crunch-slime-shop', 'Snoop Crunch Slime Shop', NULL, NULL, 'community'),
  ('snoow-slimery-katie-weiss', 'Snoow Slimery (Katie Weiss)', NULL, NULL, 'community'),
  ('soft-punk-slime-senpai', 'Soft Punk Slime Senpai', 'softpunkslime.com', '@softpunkslime', 'community'),
  ('the-slime-bakery', 'The Slime Bakery', NULL, NULL, 'community'),
  ('the-slime-playground', 'The Slime Playground', 'theslimeplayground.com', '@theslimeplaygroundshop', 'community'),
  ('a-slime-story', 'A Slime Story', NULL, '@a_slime_story', 'community'),
  ('align-slimes', 'Align Slimes', NULL, NULL, 'community'),
  ('anathema-slime', 'Anathema Slime', NULL, '@anathemaslime', 'community'),
  ('archie-slime', 'Archie Slime', NULL, NULL, 'community'),
  ('berry-cherry-slimery', 'Berry Cherry Slimery', NULL, NULL, 'community'),
  ('blissbalm', 'BlissBalm', NULL, NULL, 'community'),
  ('bowtique-slimes', 'Bowtique Slimes', NULL, NULL, 'community'),
  ('brooklyn-slime', 'Brooklyn Slime', 'brooklynslime.com', NULL, 'community'),
  ('butter-babe-slimes', 'Butter Babe Slimes', NULL, NULL, 'community'),
  ('ceces-slime-shop', 'Cece''s Slime Shop', NULL, NULL, 'community'),
  ('cloudy-skye-slimes', 'Cloudy Skye Slimes', NULL, NULL, 'community'),
  ('cosmic-slimez', 'Cosmic Slimez', NULL, NULL, 'community'),
  ('cozmic-slimez-co', 'Cozmic Slimez Co', NULL, NULL, 'community'),
  ('cupcake-slimes', 'Cupcake Slimes', NULL, NULL, 'community'),
  ('dear-slime', 'Dear Slime', NULL, NULL, 'community'),
  ('earthslime', 'EarthSlime', NULL, '@earthslimeuk', 'community'),
  ('enzo-burns-slime', 'Enzo Burns Slime', NULL, NULL, 'community'),
  ('fizzy-slime-co', 'Fizzy Slime Co', NULL, NULL, 'community'),
  ('floam-slimess', 'Floam Slimess', NULL, NULL, 'community'),
  ('floofy-slimez', 'Floofy Slimez', NULL, '@_floofy.slimez_', 'community'),
  ('fuwa-slimes', 'Fuwa Slimes', 'fuwaslimes.com', NULL, 'community'),
  ('gaza-slime', 'Gaza Slime', NULL, '@gazaslime', 'community'),
  ('glimmer-goo-slime', 'Glimmer Goo Slime', NULL, NULL, 'community'),
  ('glossy-panda-slimes', 'Glossy Panda Slimes', NULL, NULL, 'community'),
  ('gooberry-slimes', 'Gooberry Slimes', NULL, NULL, 'community'),
  ('gtcreation-slime', 'GTCREATION Slime', 'gtcreationslime.shop', NULL, 'community'),
  ('happykitscorner', 'HappyKitsCorner', NULL, NULL, 'community'),
  ('happylife-magic-shop', 'Happylife Magic Shop', NULL, NULL, 'community'),
  ('hippocampe-slimes', 'Hippocampe Slimes', 'hippocampeslimes.com', NULL, 'community'),
  ('holly-laing-slimes', 'Holly Laing Slimes', NULL, NULL, 'community'),
  ('honey-bee-slimes', 'Honey Bee Slimes', NULL, NULL, 'community'),
  ('honeysuckle-creations', 'Honeysuckle Creations', NULL, NULL, 'community'),
  ('itskristii', 'ItsKristii', NULL, NULL, 'community'),
  ('jelly-bee-slime', 'Jelly Bee Slime', NULL, NULL, 'community'),
  ('jigglypoofz-slimes', 'JigglyPoofz Slimes', NULL, NULL, 'community'),
  ('justslimemylife', 'JustSlimeMyLife', NULL, NULL, 'community'),
  ('katie-fang-slime', 'Katie Fang Slime', NULL, NULL, 'community'),
  ('king-slime-co', 'King Slime Co', NULL, '@king.slime.co', 'community'),
  ('konrad-slimes', 'Konrad Slimes', NULL, NULL, 'community'),
  ('ksc-slime', 'KSC Slime', NULL, NULL, 'community'),
  ('lemon-and-lime-slimes', 'Lemon and Lime Slimes', 'lemonsandlimeslimes.com', '@lemon_andlimeslimes', 'community'),
  ('lily-vanilly-slime', 'Lily Vanilly Slime', NULL, NULL, 'community'),
  ('luna-slime-co', 'Luna Slime Co', NULL, NULL, 'community'),
  ('madz-slimes', 'Madz Slimes', NULL, NULL, 'community'),
  ('milky-way-slimes', 'Milky Way Slimes', NULL, NULL, 'community'),
  ('minty-fresh-slimes', 'Minty Fresh Slimes', NULL, NULL, 'community'),
  ('mishmash-slime-shop', 'MishMash Slime Shop', NULL, NULL, 'community'),
  ('mochi-slime-uk', 'Mochi Slime UK', 'mochislime.co.uk', '@mochislimeuk', 'community'),
  ('ocean-hippy-slimes', 'Ocean Hippy Slimes', NULL, NULL, 'community'),
  ('olee-3d-art', 'Olee 3D Art', NULL, NULL, 'community'),
  ('oozed-slime', 'Oozed Slime', 'oozedslime.co.uk', NULL, 'community'),
  ('peach-pit-slimes', 'Peach Pit Slimes', NULL, NULL, 'community'),
  ('peachy-keen-slimes', 'Peachy Keen Slimes', NULL, NULL, 'community'),
  ('philosophy-in-making', 'Philosophy In Making', NULL, NULL, 'community'),
  ('poppy-mello-slimes', 'Poppy Mello Slimes', NULL, NULL, 'community'),
  ('poptartes-slimes', 'Poptartes Slimes', NULL, '@pop.tarteslimes', 'community'),
  ('printed-place-co', 'Printed Place Co', NULL, NULL, 'community'),
  ('pugs-love-slime', 'Pugs Love Slime', NULL, '@pugsloveislime', 'community'),
  ('pumpkin-slime-co', 'Pumpkin Slime Co', NULL, NULL, 'community'),
  ('putty-cream', 'Putty Cream', NULL, NULL, 'community'),
  ('rainbow-slimesz', 'Rainbow Slimesz', NULL, NULL, 'community'),
  ('razberryslimeco', 'RazberrySlimeCo', NULL, '@razberryslimeco', 'community'),
  ('royal-slime-shop-ca', 'Royal Slime Shop CA', NULL, NULL, 'community'),
  ('samantha-slime-shop', 'Samantha Slime Shop', NULL, '@samanthaslimeshop', 'community'),
  ('silky-gem-crystal-candy', 'Silky Gem Crystal Candy', NULL, NULL, 'community'),
  ('slime-bee', 'Slime Bee', NULL, NULL, 'community'),
  ('slime-by-sara', 'Slime by Sara', NULL, '@slimebysara_', 'community'),
  ('slime-clouds', 'Slime Clouds', NULL, NULL, 'community'),
  ('slime-dazzle', 'Slime Dazzle', NULL, NULL, 'community'),
  ('slime-dreams', 'Slime Dreams', NULL, NULL, 'community'),
  ('slime-elevated-llc', 'Slime Elevated LLC', NULL, NULL, 'community'),
  ('slime-fantasy-co', 'Slime Fantasy Co', NULL, NULL, 'community'),
  ('slime-galaxy', 'Slime Galaxy', NULL, NULL, 'community'),
  ('slime-haven', 'Slime Haven', NULL, NULL, 'community'),
  ('slime-jungle', 'Slime Jungle', NULL, NULL, 'community'),
  ('slime-kingdom', 'Slime Kingdom', NULL, NULL, 'community'),
  ('slime-labs-uk', 'Slime Labs UK', 'slimelabs.co.uk', NULL, 'community'),
  ('slime-marshmallows', 'Slime Marshmallows', 'slimemarshmallows.com', NULL, 'community'),
  ('slime-paradise', 'Slime Paradise', NULL, NULL, 'community'),
  ('slime-princess-shop', 'Slime Princess Shop', NULL, NULL, 'community'),
  ('slime-screwball', 'Slime Screwball', 'slimescrewball.co.uk', NULL, 'community'),
  ('slime-shop-by-madelyn', 'Slime Shop by Madelyn', NULL, NULL, 'community'),
  ('slime-universe', 'Slime Universe', NULL, NULL, 'community'),
  ('slime-yoda', 'Slime Yoda', 'slimeyodashop.com', NULL, 'community'),
  ('slimeful', 'Slimeful', 'slimeful.life', '@slimeful.life', 'community'),
  ('slimentine', 'Slimentine', NULL, NULL, 'community'),
  ('slimerella-slime-shop', 'Slimerella Slime Shop', 'slimerellaslimeshop.com', NULL, 'community'),
  ('slimes-by-milo', 'Slimes by Milo', NULL, '@slimesbymilo', 'community'),
  ('slimeworks-slime-shop', 'SlimeWorks Slime Shop', NULL, NULL, 'community'),
  ('slimy-goodz', 'Slimy Goodz', NULL, NULL, 'community'),
  ('slimy-jester-shop', 'Slimy Jester Shop', NULL, NULL, 'community'),
  ('slimy-super-fluffy', 'Slimy Super Fluffy', NULL, NULL, 'community'),
  ('slimy-unicorn-customs', 'Slimy Unicorn Customs', NULL, NULL, 'community'),
  ('sparkle-slime-co', 'Sparkle Slime Co', NULL, NULL, 'community'),
  ('squid-slime-shop', 'Squid Slime Shop', NULL, NULL, 'community'),
  ('starlight-slimes', 'Starlight Slimes', NULL, NULL, 'community'),
  ('stress-pop-slime', 'Stress Pop Slime', NULL, NULL, 'community'),
  ('sugar-cookie-slimes', 'Sugar Cookie Slimes', NULL, NULL, 'community'),
  ('sugar-slime', 'Sugar Slime', NULL, NULL, 'community'),
  ('sustainaslimes', 'Sustainaslimes', 'sustainaslimes.com', NULL, 'community'),
  ('sweet-tooth-slimes', 'Sweet Tooth Slimes', NULL, NULL, 'community'),
  ('tessa-bunny', 'Tessa Bunny', 'tessabunny.com', NULL, 'community'),
  ('the-introverted-craft', 'The Introverted Craft', NULL, NULL, 'community'),
  ('the-sliime-shoppe', 'The Sliime Shoppe', NULL, NULL, 'community'),
  ('the-slime-company', 'The Slime Company', 'theslimecompany.co.uk', NULL, 'community'),
  ('the-slime-jar', 'The Slime Jar', NULL, NULL, 'community'),
  ('the-slime-queen', 'The Slime Queen', NULL, NULL, 'community'),
  ('the-slime-shop-uk', 'The Slime Shop UK', 'theslimeshop.co.uk', NULL, 'community'),
  ('the-slime-tailor', 'The Slime Tailor', NULL, NULL, 'community'),
  ('the-sublime-slimez', 'The Sublime Slimez', NULL, NULL, 'community'),
  ('totogi-slime', 'Totogi Slime', NULL, '@totogislime', 'community'),
  ('toxic-slime-co', 'Toxic Slime Co', NULL, NULL, 'community'),
  ('velvet-slime-shop', 'Velvet Slime Shop', NULL, NULL, 'community'),
  ('whipped-cream-slimes', 'Whipped Cream Slimes', NULL, NULL, 'community'),
  ('wonderland-slimes', 'Wonderland Slimes', NULL, NULL, 'community'),
  ('yc-slimez', 'YC Slimez', NULL, NULL, 'community'),
  ('zuzu-slimes', 'Zuzu Slimes', NULL, NULL, 'community'),
  ('alpacaa-slimey', 'Alpacaa Slimey', 'alpacaaslimey.com.au', NULL, 'community'),
  ('aussie-slime-co', 'Aussie Slime Co', 'aussieslimeco.com.au', NULL, 'community'),
  ('avocado-slimeez', 'Avocado Slimeez', 'avocadoslimeez.com', NULL, 'community'),
  ('cozy-slime', 'COZY Slime', 'Unknown (via SeoulGAGE)', NULL, 'community'),
  ('cyber-slimes', 'Cyber Slimes', NULL, NULL, 'community'),
  ('diy-slime-shop-ny', 'D.I.Y. Slime Shop NY', 'diyslimeshopny.com', NULL, 'community'),
  ('daiso-slime', 'Daiso Slime', NULL, NULL, 'community'),
  ('elmers-slime', 'Elmer''s Slime', NULL, NULL, 'community'),
  ('gooru-slime', 'Gooru Slime', 'gooruslime.com', NULL, 'community'),
  ('guigui-slime-moose-toys', 'GuiGui Slime (Moose Toys)', NULL, '@guiguislime_', 'community'),
  ('hong-giang-diy-slime', 'Hong Giang DIY Slime', NULL, NULL, 'community'),
  ('jessica-effendy-slime', 'Jessica Effendy Slime', NULL, NULL, 'community'),
  ('joybox-slime', 'Joybox Slime', NULL, '@joyboxslime', 'community'),
  ('just-ameerah', 'Just Ameerah', NULL, NULL, 'community'),
  ('king-slime-company-br', 'King Slime Company (BR)', NULL, '@king.slime.company', 'community'),
  ('love-slimes-co', 'Love Slimes Co', NULL, NULL, 'community'),
  ('maou-slimes', 'Maou Slimes', NULL, '@maou.slimes', 'community'),
  ('meli-melo', 'Meli & Melo', 'meliandmelo.com', NULL, 'community'),
  ('momone', 'MOMONE', 'Unknown (via SeoulGAGE)', NULL, 'community'),
  ('mr-chicken-slimes', 'Mr Chicken Slimes', 'mrchickenslimes.com', NULL, 'community'),
  ('noras-slimery', 'Nora''s Slimery', 'norasslimery.com', NULL, 'community'),
  ('oozapalooza', 'OOZAPALOOZA', NULL, NULL, 'community'),
  ('patty-slimes', 'Patty Slimes', NULL, NULL, 'community'),
  ('scoopi', 'Scoopi', 'scoopi.com.au', NULL, 'community'),
  ('silly-squish-slime', 'Silly Squish Slime', NULL, NULL, 'community'),
  ('slime-by-zahra', 'Slime by Zahra', 'slimebyzahra.com', NULL, 'community'),
  ('slime-community-mga', 'Slime Community (MGA)', 'slimecommunity.com', NULL, 'community'),
  ('slime-factory-india', 'Slime Factory India', NULL, '@slime.factory.india', 'community'),
  ('slime-mania-au', 'Slime Mania AU', 'slimemania.com.au', NULL, 'community'),
  ('slime-shack-au', 'Slime Shack AU', 'slimeshack.com.au', NULL, 'community'),
  ('slime-zone-and-more', 'Slime Zone and More', 'slimezoneandmorefranchise.com', NULL, 'community'),
  ('slimedrops', 'Slimedrops', 'slimedrops.co', NULL, 'community'),
  ('slimeminator', 'Slimeminator', 'slimeminator.com', NULL, 'community'),
  ('slimes-mel-melissa-seabra', 'Slimes Mel (Melissa Seabra)', NULL, NULL, 'community'),
  ('slimeslimede', 'SlimeSlime.de', 'slimeslime.de', NULL, 'community'),
  ('sloomoo-institute', 'Sloomoo Institute', 'sloomooinstitute.com', NULL, 'community'),
  ('sophies-slime-factory', 'Sophie''s Slime Factory', NULL, NULL, 'community'),
  ('squishy-squashy-slimes', 'Squishy Squashy Slimes', NULL, NULL, 'community'),
  ('sticky-sparkle-slime', 'Sticky Sparkle Slime', 'stickysparkleslime.com', NULL, 'community'),
  ('talisa-tossell', 'Talisa Tossell', NULL, NULL, 'community'),
  ('the-slime-factory-miami', 'The Slime Factory Miami', NULL, NULL, 'community'),
  ('the-slime-kitchen', 'The Slime Kitchen', 'theslimekitchen.com', NULL, 'community'),
  ('the-slime-space', 'The Slime Space', NULL, '@the.slime.space', 'community'),
  ('wuwa-slimes', 'Wuwa Slimes', 'wuwaslimes.com', NULL, 'community'),
  ('zs-mobile-slime-factory', 'Z''s Mobile Slime Factory', 'mobileslimefactory.com', NULL, 'community')
ON CONFLICT (slug) DO NOTHING;